project_id = "cnofbtrtyiilmhlrashl"

[functions.orders-api]
verify_jwt = false

[functions.notify-admin-new-user]
verify_jwt = false

[functions.send-completed-order-email]
verify_jwt = false

[functions.send-order-notifications]
verify_jwt = false

[functions.order-insights]
verify_jwt = false

[functions.zoho-auth]
verify_jwt = false

[functions.zoho-sync]
verify_jwt = false

[functions.zoho-webhook]
verify_jwt = false